repos:
  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.9.9
    hooks:
      - id: uv-lock

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.5
    hooks:
      - id: ruff-check
        args:
          - --fix
      - id: ruff-format

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.18.2
    hooks:
      - id: mypy
        name: mypy --strict
        args:
          - --strict
          - src/aiotgbot
          - tests
        pass_filenames: false
        additional_dependencies:
          - aiofreqlimit>=0.2.2,<0.3.0
          - aiohttp>=3.13.2,<4.0.0
          - aiojobs>=1.4.0,<2.0.0
          - tenacity>=9.1.2,<10.0.0
          - frozenlist>=1.8.0,<2.0.0
          - msgspec>=0.19.0,<0.20.0
          - yarl>=1.22.0,<2.0.0
          - aiosqlite>=0.21.0,<0.22.0
          - sqlalchemy>=2.0.44,<3.0.0
          - cryptography>=46.0.0,<47.0.0
          - pytest>=9.0.1,<10.0.0
          - pytest-asyncio>=1.3.0,<2.0.0
          - more-itertools>=10.8.0,<11.0.0
          - types-setuptools>=80.9.0,<81.0.0

  - repo: https://github.com/DetachHead/basedpyright-prek-mirror
    rev: 1.33.0
    hooks:
      - id: basedpyright
        pass_filenames: false
        additional_dependencies:
          - aiofreqlimit>=0.2.2,<0.3.0
          - aiohttp>=3.13.2,<4.0.0
          - aiojobs>=1.4.0,<2.0.0
          - tenacity>=9.1.2,<10.0.0
          - frozenlist>=1.8.0,<2.0.0
          - msgspec>=0.19.0,<0.20.0
          - yarl>=1.22.0,<2.0.0
          - aiosqlite>=0.21.0,<0.22.0
          - sqlalchemy>=2.0.44,<3.0.0
          - cryptography>=46.0.0,<47.0.0

  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: uv run --group test pytest
        language: system
        pass_filenames: false
        stages: [commit]
